// Questo file contiene le costanti globali dell'applicazione

// Elenco dei cardinali papabili
const CARDINALI = [
  'Mykola Byčok - (elettore) -  Ucraina - 45 anni',
  'Giorgio Marengo - (elettore) -  Italia - 50 anni',
  'Américo Manuel Alves Aguiar - (elettore) -  Portogallo - 51 anni',
  'George Jacob Koovakad - (elettore) -  India - 51 anni',
  'Rolandas Makrickas - (elettore) -  Lituania - 53 anni',
  'Frank Leo - (elettore) -  Canada - 53 anni',
  'Baldassare Reina - (elettore) -  Italia - 54 anni',
  'François-Xavier Bustillo - (elettore) -  Spagna - 56 anni',
  'Virgilio do Carmo da Silva - (elettore) -  Timor Est - 57 anni',
  'Paulo Cezar Costa - (elettore) -  Brasile - 57 anni',
  'Dieudonné Nzapalainga - (elettore) -  Repubblica Centrafricana - 58 anni',
  'Roberto Repole - (elettore) -  Italia - 58 anni',
  'José Tolentino Calaça de Mendonça - (elettore) -  Portogallo - 59 anni',
  'Mauro Gambetti - (elettore) -  Italia - 59 anni',
  'José Cobo Cano - (elettore) -  Spagna - 59 anni',
  'Pierbattista Pizzaballa - (elettore) -  Italia - 60 anni',
  'Fabio Baggio - (elettore) -  Italia - 60 anni',
  'Augusto Paolo Lojudice - (elettore) -  Italia - 60 anni',
  'Grzegorz Ryś - (elettore) -  Polonia - 61 anni',
  'Stephen Ameyu Martin Mulla - (elettore) -  Sudan del Sud - 61 anni',
  'Konrad Krajewski - (elettore) -  Polonia - 61 anni',
  'Dominique Joseph Mathieu - (elettore) -  Belgio - 61 anni',
  'Peter Ebere Okpaleke - (elettore) -  Nigeria - 62 anni',
  'Domenico Battaglia - (elettore) -  Italia - 62 anni',
  'Víctor Manuel Fernández - (elettore) -  Argentina - 62 anni',
  'Jean-Paul Vesco - (elettore) -  Francia - 63 anni',
  'Luis José Rueda Aparicio - (elettore) -  Colombia - 63 anni',
  'Soane Patita Paini Mafi - (elettore) -  Tonga - 63 anni',
  'Ignace Bessi Dogbo - (elettore) -  Costa d\'Avorio - 63 anni',
  'Anthony Poola - (elettore) -  India - 63 anni',
  'Jaime Spengler - (elettore) -  Brasile - 64 anni',
  'Ángel Fernández Artime - (elettore) -  Spagna - 64 anni',
  'Protase Rugambwa - (elettore) -  Tanzania - 64 anni',
  'Fridolin Ambongo Besungu - (elettore) -  Rep. Dem. del Congo - 65 anni',
  'Sérgio da Rocha - (elettore) -  Brasile - 65 anni',
  'Stephen Chow Sau-yan - (elettore) -  Cina - 65 anni',
  'Daniel Fernando Sturla Berhouet - (elettore) -  Uruguay - 65 anni',
  'Isaac Cleemis Thottunkal - (elettore) -  India - 65 anni',
  'Pablo Virgilio Siongco David - (elettore) -  Filippine - 66 anni',
  'Jean-Marc Aveline - (elettore) -  Francia - 66 anni',
  'Chibly Langlois - (elettore) -  Haiti - 66 anni',
  'Antoine Kambanda - (elettore) -  Ruanda - 66 anni',
  'Tarcisius Isao Kikuchi - (elettore) -  Giappone - 66 anni',
  'Ángel Sixto Rossi - (elettore) -  Argentina - 66 anni',
  'Jean-Claude Höllerich - (elettore) -  Lussemburgo - 66 anni',
  'Gérald Cyprien Lacroix - (elettore) -  Canada - 67 anni',
  'William Seng Chye Goh - (elettore) -  Singapore - 67 anni',
  'Luis Antonio Gokim Tagle - (elettore) -  Filippine - 67 anni',
  'Fernando Natalio Chomalí Garib - (elettore) -  Cile - 68 anni',
  'Mario Grech - (elettore) -  Malta - 68 anni',
  'John Ribat - (elettore) -  Papua Nuova Guinea - 68 anni',
  'Stephen Brislin - (elettore) -  Sudafrica - 68 anni',
  'László Német - (elettore) -  Serbia - 68 anni',
  'Rainer Maria Woelki - (elettore) -  Germania - 68 anni',
  'Luis Gerardo Cabrera Herrera - (elettore) -  Ecuador - 69 anni',
  'Matteo Zuppi - (elettore) -  Italia - 69 anni',
  'Claudio Gugerotti - (elettore) -  Italia - 69 anni',
  'Robert Francis Prevost - (elettore) -  Stati Uniti d\'America - 69 anni',
  'Pietro Parolin - (elettore) -  Italia - 70 anni',
  'Désiré Tsarahazana - (elettore) -  Madagascar - 70 anni',
  'Robert Walter McElroy - (elettore) -  Stati Uniti d\'America - 71 anni',
  'Angelo De Donatis - (elettore) -  Italia - 71 anni',
  'Reinhard Marx - (elettore) -  Germania - 71 anni',
  'Willem Jacobus Eĳk - (elettore) -  Paesi Bassi - 71 anni',
  'Filipe Neri António Sebastião do Rosário Ferrão - (elettore) -  India - 72 anni',
  'Péter Erdő - (elettore) -  Ungheria - 72 anni',
  'Vicente Bokalic Iglic - (elettore) -  Argentina - 72 anni',
  'Cristóbal López Romero - (elettore) -  Spagna - 72 anni',
  'Joseph William Tobin - (elettore) -  Stati Uniti d\'America - 72 anni',
  'Jose Fuerte Advincula - (elettore) -  Filippine - 73 anni',
  'Dominique Mamberti - (elettore) -  Francia - 73 anni',
  'Lazarus You Heung-sik - (elettore) -  Corea del Sud - 73 anni',
  'Sebastian Francis - (elettore) -  Malaysia - 73 anni',
  'Adalberto Martínez Flores - (elettore) -  Paraguay - 73 anni',
  'Leonardo Ulrich Steiner - (elettore) -  Brasile - 74 anni',
  'Philippe Barbarin - (elettore) -  Francia - 74 anni',
  'Oscar Cantoni - (elettore) -  Italia - 74 anni',
  'Ignatius Suharyo Hardjoatmodjo - (elettore) -  Indonesia - 74 anni',
  'Orani João Tempesta - (elettore) -  Brasile - 74 anni',
  'Kurt Koch - (elettore) -  Svizzera - 75 anni',
  'Arthur Roche - (elettore) -  Regno Unito - 75 anni',
  'Carlos Gustavo Castillo Mattasoglio - (elettore) -  Perù - 75 anni',
  'Timothy Dolan - (elettore) -  Stati Uniti d\'America - 75 anni',
  'Kazimierz Nycz - (elettore) -  Polonia - 75 anni',
  'Carlos Aguiar Retes - (elettore) -  Messico - 75 anni',
  'Arlindo Gomes Furtado - (elettore) -  Capo Verde - 75 anni',
  'James Michael Harvey - (elettore) -  Stati Uniti d\'America - 75 anni',
  'Anders Arborelius - (elettore) -  Svezia - 75 anni',
  'Odilo Pedro Scherer - (elettore) -  Brasile - 75 anni',
  'Francis Xavier Kriengsak Kovithavanij - (elettore) -  Thailandia - 75 anni',
  'Daniel Nicholas DiNardo - (elettore) -  Stati Uniti d\'America - 75 anni',
  'Josip Bozanic - (elettore) -  Croazia - 76 anni',
  'Blase Joseph Cupich - (elettore) -  Stati Uniti d\'America - 76 anni',
  'Leopoldo José Brenes Solórzano - (elettore) -  Nicaragua - 76 anni',
  'Thomas Aquino Manyo Maeda - (elettore) -  Giappone - 76 anni',
  'José Francisco Robles Ortega - (elettore) -  Messico - 76 anni',
  'Charles Maung Bo - (elettore) -  Birmania - 76 anni',
  'Peter Kodwo Appiah Turkson - (elettore) -  Ghana - 76 anni',
  'Giuseppe Petrocchi - (elettore) -  Italia - 76 anni',
  'Manuel José Macário do Nascimento Clemente - (elettore) -  Portogallo - 76 anni',
  'Berhaneyesus Demerew Souraphiel - (elettore) -  Etiopia - 76 anni',
  'Juan de la Caridad García Rodríguez - (elettore) -  Cuba - 76 anni',
  'Louis Raphaël I Sako - (elettore) -  Iraq - 76 anni',
  'Raymond Leo Burke - (elettore) -  Stati Uniti d\'America - 76 anni',
  'John Atcherley Dew - (elettore) -  Nuova Zelanda - 76 anni',
  'Gerhard Ludwig Müller - (elettore) -  Germania - 77 anni',
  'Marcello Semeraro - (elettore) -  Italia - 77 anni',
  'Wilton Daniel Gregory - (elettore) -  Stati Uniti d\'America - 77 anni',
  'Mario Aurelio Poli - (elettore) -  Argentina - 77 anni',
  'Albert Malcolm Ranjith Patabendige Don - (elettore) -  Sri Lanka - 77 anni',
  'Kevin Joseph Farrell - (elettore) -  Stati Uniti d\'America - 77 anni',
  'Álvaro Leonel Ramazzini Imeri - (elettore) -  Guatemala - 77 anni',
  'Jozef De Kesel - (elettore) -  Belgio - 77 anni',
  'António Augusto dos Santos Marto - (elettore) -  Portogallo - 77 anni',
  'João Braz de Aviz - (elettore) -  Brasile - 78 anni',
  'Giuseppe Betori - (elettore) -  Italia - 78 anni',
  'Emil Paul Tscherrig - (elettore) -  Svizzera - 78 anni',
  'Thomas Christopher Collins - (elettore) -  Canada - 78 anni',
  'Michael Czerny - (elettore) -  Canada - 78 anni',
  'Francesco Montenegro - (elettore) -  Italia - 78 anni',
  'Juan José Omella - (elettore) -  Spagna - 79 anni',
  'Fernando Filoni - (elettore) -  Italia - 79 anni',
  'Christophe Pierre - (elettore) -  Francia - 79 anni',
  'Mario Zenari - (elettore) -  Italia - 79 anni',
  'John Njue - (elettore) -  Kenya - 79 anni[4]',
  'Philippe Nakellentuba Ouédraogo - (elettore) -  Burkina Faso - 79 anni',
  'Jean-Pierre Kutwa - (elettore) -  Costa d\'Avorio - 79 anni',
  'Vincent Nichols - (elettore) -  Regno Unito - 79 anni',
  'Antonio Cañizares Llovera - (elettore) -  Spagna - 79 anni',
  'Vinko Puljić - (elettore) -  Bosnia ed Erzegovina - 79 anni',
  'Timothy Peter Joseph Radcliffe - (elettore) -  Regno Unito - 79 anni',
  'Joseph Coutts - (elettore) -  Pakistan - 79 anni',
  'Stanisław Ryłko - (elettore) -  Polonia - 79 anni',
  'Robert Sarah - (elettore) -  Guinea - 79 anni',
  'Carlos Osoro Sierra - (elettore) -  Spagna - 79 anni',
  'Giovanni Angelo Becciu[6] - (non elettore) -  Italia - 76 anni',
  'George Alencherry - (non elettore) -  India - 80 anni',
  'Celestino Aós Braco - (non elettore) -  Cile - 80 anni',
  'Fernando Vérgez Alzaga - (non elettore) -  Spagna - 80 anni',
  'Christoph Schönborn - (non elettore) -  Austria - 80 anni',
  'Oswald Gracias - (non elettore) -  India - 80 anni',
  'Baltazar Enrique Porras Cardozo - (non elettore) -  Venezuela - 80 anni',
  'Jean-Pierre Ricard - (non elettore) -  Francia - 80 anni',
  'Mauro Piacenza - (non elettore) -  Italia - 80 anni',
  'Polycarp Pengo - (non elettore) -  Tanzania - 80 anni',
  'Sean Patrick O\'Malley - (non elettore) -  Stati Uniti d\'America - 80 anni',
  'Marc Ouellet - (non elettore) -  Canada - 80 anni',
  'Luis Francisco Ladaria Ferrer - (non elettore) -  Spagna - 81 anni',
  'Louis-Marie Ling Mangkhanekhoun - (non elettore) -  Laos - 81 anni',
  'José Luis Lacunza Maestrojuán - (non elettore) -  Panamá - 81 anni',
  'Pedro Ricardo Barreto Jimeno - (non elettore) -  Perù - 81 anni',
  'John Olorunfemi Onaiyekan - (non elettore) -  Nigeria - 81 anni',
  'Juan Luis Cipriani Thorne - (non elettore) -  Perù - 81 anni',
  'Andrew Yeom Soo-jung - (non elettore) -  Corea del Sud - 81 anni',
  'Jean Zerbo - (non elettore) -  Mali - 81 anni',
  'Leonardo Sandri - (non elettore) -  Argentina - 81 anni',
  'Patrick D\'Rozario - (non elettore) -  Bangladesh - 81 anni',
  'Angelo Comastri - (non elettore) -  Italia - 81 anni',
  'Giuseppe Versaldi - (non elettore) -  Italia - 81 anni',
  'Crescenzio Sepe - (non elettore) -  Italia - 81 anni',
  'Dominik Duka O.P. - (non elettore) -  Repubblica Ceca - 81 anni',
  'Domenico Calcagno - (non elettore) -  Italia - 82 anni',
  'Angelo Bagnasco - (non elettore) -  Italia - 82 anni',
  'Óscar Andrés Rodríguez Maradiaga - (non elettore) -  Honduras - 82 anni',
  'André Vingt-Trois - (non elettore) -  Francia - 82 anni',
  'Gianfranco Ravasi - (non elettore) -  Italia - 82 anni',
  'Giuseppe Bertello - (non elettore) -  Italia - 82 anni',
  'Rubén Salazar Gómez - (non elettore) -  Colombia - 82 anni',
  'Gregorio Rosa Chávez - (non elettore) -  El Salvador - 82 anni',
  'Arrigo Miglio - (non elettore) -  Italia - 82 anni',
  'Gianfranco Ghirlanda - (non elettore) -  Italia - 82 anni',
  'Norberto Rivera Carrera - (non elettore) -  Messico - 82 anni',
  'Gualtiero Bassetti - (non elettore) -  Italia - 83 anni',
  'Ricardo Blázquez Pérez - (non elettore) -  Spagna - 83 anni',
  'Jorge Enrique Jiménez Carvajal - (non elettore) -  Colombia - 83 anni',
  'Fortunato Frezza - (non elettore) -  Italia - 83 anni',
  'Ricardo Ezzati Andrello - (non elettore) -  Cile - 83 anni',
  'Angelo Scola - (non elettore) -  Italia - 83 anni',
  'Beniamino Stella - (non elettore) -  Italia - 83 anni',
  'Maurice Piat - (non elettore) -  Mauritius - 83 anni',
  'Wilfrid Fox Napier - (non elettore) -  Sudafrica - 84 anni',
  'Gabriel Zubeir Wako - (non elettore) -  Sudan - 84 anni',
  'Donald William Wuerl - (non elettore) -  Stati Uniti d\'America - 84 anni',
  'Silvano Maria Tomasi - (non elettore) -  Italia - 84 anni',
  'Lorenzo Baldisseri - (non elettore) -  Italia - 84 anni',
  'Agostino Marchetto - (non elettore) -  Italia - 84 anni',
  'Enrico Feroci - (non elettore) -  Italia - 84 anni',
  'Felipe Arizmendi Esquivel - (non elettore) -  Messico - 84 anni',
  'Agostino Vallini - (non elettore) -  Italia - 85 anni',
  'Béchara Boutros Raï - (non elettore) -  Libano - 85 anni',
  'Edoardo Menichelli - (non elettore) -  Italia - 85 anni',
  'Seán Baptist Brady - (non elettore) -  Irlanda - 85 anni',
  'John Tong Hon - (non elettore) -  Cina - 85 anni',
  'Diego Rafael Padrón Sánchez - (non elettore) -  Venezuela - 85 anni',
  'Stanisław Dziwisz - (non elettore) -  Polonia - 85 anni',
  'Edwin Frederick O\'Brien - (non elettore) -  Stati Uniti d\'America - 86 anni',
  'Orlando Beltran Quevedo - (non elettore) -  Filippine - 86 anni',
  'Alberto Suárez Inda - (non elettore) -  Messico - 86 anni',
  'Sigitas Tamkevicius - (non elettore) -  Lituania - 86 anni',
  'Aquilino Bocos Merino - (non elettore) -  Spagna - 86 anni',
  'Pierre Nguyên Văn Nhon - (non elettore) -  Vietnam - 87 anni',
  'Manuel Monteiro de Castro - (non elettore) -  Portogallo - 87 anni',
  'Francesco Coccopalmerio - (non elettore) -  Italia - 87 anni',
  'Paolo Romeo - (non elettore) -  Italia - 87 anni',
  'Antonio Maria Vegliò - (non elettore) -  Italia - 87 anni',
  'Michael Louis Fitzgerald - (non elettore) -  Regno Unito - 87 anni',
  'Lluís Martinez Sistach - (non elettore) -  Spagna - 87 anni',
  'Toribio Ticona Porco - (non elettore) -  Bolivia - 87 anni',
  'Raymundo Damasceno Assis - (non elettore) -  Brasile - 88 anni',
  'Audrys Juozas Bačkis - (non elettore) -  Lituania - 88 anni',
  'Théodore-Adrien Sarr - (non elettore) -  Senegal - 88 anni',
  'Ennio Antonelli - (non elettore) -  Italia - 88 anni',
  'Nicolás de Jesús López Rodríguez - (non elettore) -  Repubblica Dominicana - 88 anni',
  'Antonio María Rouco Varela - (non elettore) -  Spagna - 88 anni',
  'Anthony Olubunmi Okogie - (non elettore) -  Nigeria - 88 anni',
  'Roger Michael Mahony - (non elettore) -  Stati Uniti d\'America - 89 anni',
  'Santos Abril y Castelló - (non elettore) -  Spagna - 89 anni',
  'Justin Francis Rigali - (non elettore) -  Stati Uniti d\'America - 90 anni',
  'Giovanni Lajolo - (non elettore) -  Italia - 90 anni',
  'Julius Riyadi Darmaatmadja - (non elettore) -  Indonesia - 90 anni',
  'Tarcisio Bertone - (non elettore) -  Italia - 90 anni',
  'Luis Héctor Villalba - (non elettore) -  Argentina - 90 anni',
  'Franc Rodé - (non elettore) -  Slovenia - 90 anni',
  'Raniero Cantalamessa - (non elettore) -  Italia - 90 anni',
  'Francesco Monterisi - (non elettore) -  Italia - 90 anni',
  'Jean-Baptiste Pham Minh Mân - (non elettore) -  Vietnam - 91 anni',
  'Giovanni Battista Re - (non elettore) -  Italia - 91 anni',
  'Raffaele Farina - (non elettore) -  Italia - 91 anni',
  'Francisco Javier Errázuriz Ossa - (non elettore) -  Cile - 91 anni',
  'Juan Sandoval Íñiguez - (non elettore) -  Messico - 92 anni',
  'Walter Kasper - (non elettore) -  Germania - 92 anni',
  'Francis Arinze - (non elettore) -  Nigeria - 92 anni',
  'Gaudencio Rosales - (non elettore) -  Filippine - 92 anni',
  'Joseph Zen Ze-kiun - (non elettore) -  Cina - 93 anni',
  'José Saraiva Martins - (non elettore) -  Portogallo - 93 anni',
  'Lucian Mureșan - (non elettore) -  Romania - 93 anni',
  'Camillo Ruini - (non elettore) -  Italia - 94 anni',
  'Jānis Pujats - (non elettore) -  Lettonia - 94 anni',
  'Salvatore De Giorgi - (non elettore) -  Italia - 94 anni',
  'Paul Poupard - (non elettore) -  Francia - 94 anni',
  'Julián Herranz Casado - (non elettore) -  Spagna - 95 anni',
  'Thomas Stafford Williams - (non elettore) -  Nuova Zelanda - 95 anni',
  'Adam Joseph Maida - (non elettore) -  Stati Uniti d\'America - 95 anni',
  'Michael Michai Kitbunchu - (non elettore) -  Thailandia - 96 anni',
  'Walter Brandmüller - (non elettore) -  Germania - 96 anni',
  'Ernest Simoni - (non elettore) -  Albania - 96 anni',
  'Friedrich Wetter - (non elettore) -  Germania - 97 anni',
  'Júlio Duarte Langa - (non elettore) - Mzambico - 97 anni',
  'Luis Pascual Dri - (non elettore) -  Argentina - 98 anni',
  'Emmanuel Wamala - (non elettore) -  Uganda - 98 anni',
  'Estanislao Esteban Karlic - (non elettore) -  Argentina - 99 anni',
  'Angelo Acerbi - (non elettore) -  Italia - 99 anni',
  'altro - vescovo',
  'altro - sacerdote', 
'altro - laico'

];

// Opzioni per la fumata bianca
const OPZIONI_FUMATA = [
    { value: 'a', label: 'a) 1° giorno di conclave' },
    { value: 'b', label: 'b) 2° o 3° giorno di conclave' },
    { value: 'c', label: 'c) 4° o 5° giorno di conclave' },
    { value: 'd', label: 'd) oltre il 5° giorno' }
];

// Descrizioni delle opzioni fumata
const DESCRIZIONI_FUMATA = {
    'a': 'a) 1° giorno di conclave',
    'b': 'b) 2° o 3° giorno di conclave',
    'c': 'c) 4° o 5° giorno di conclave',
    'd': 'd) oltre il 5° giorno'
};
